service: robot-automation

frameworkVersion: '>=1.28.0 <2.0.0'

provider:
  name: aws
  runtime: go1.x
  memorySize: 128
  timeout: 1
  stage: staging
  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", "ss-stage-robot-assets" ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:GetObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "ss-stage-robot-assets"
            - "/*"
    - Effect: "Allow"
      Action:
        - "events:*"
      Resource: "*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  s3parser:
    handler: bin/s3parser
    events:
      - http:
          path: /logs
          method: get
          cors:
            origin: '*'
  scheduler:
    handler: bin/scheduler
    events:
      - http:
          path: cron
          method: get
          cors:
            origin: '*'
#      - http:
#          path: /
#          method: post
#          cors:
#            origin: '*'
  manual:
    handler: bin/manual
    events:
      - http:
          path: /
          method: post
          cors:
            origin: '*'
